version: '3.8'
name: demo-datadog
services:

  demo-datadog-seq:
    image: datalust/seq:latest
    container_name: demo-datadog-seq
    restart: unless-stopped
    ports:
      - 5380:80   # UI
      - 5341:5341 # Data ingest
    environment:      
      - ACCEPT_EULA=Y

  demo-datadog-jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    restart: always
    ports:
      - 16686:16686 # UI: http://localhost:16686/search
      #- 4317:55680
      #- 55680:55680 # OTLP receiver listening on port 
      #- 13133:13133 # Health check port       
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '9411:9411'
